name: Linting
# Linting tools use `pyproject.toml` for config.

on:
  - pull_request

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Create virtual environment
        run: uv venv

      - name: Install requirements
        run: |
          uv pip install typer-invoke
          uv run inv pip install dev

      - name: Linting
        run: uv run inv lint all
